# Building all the images
script:
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user  
        # - docker build -t udagram-frontend ./udagram-frontend
        - docker build -t udagram-reverseproxy ./udagram-reverseproxy


        # Tagging
        - docker tag udagram-api-feed iainmosima/udagram-api-feed:v1
        - docker tag udagram-api-user iainmosima/udagram-api-user:v1
         # - docker tag udagram-api-frontend iainmosima/udagram-frontend:v1
        - docker tag udagram-reverseproxy iainmosima/udagram-reverseproxy:v1

after_succes:
        # logging credentials
         - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

        # pushing
        - docker push iainmosima/udagram-api-feed:v1
        - docker push iainmosima/udagram-api-user:v1
        #- docker push iainmosima/udagram-frontend:v1
        - docker push iainmosima/udagram-reverseproxy:v1

