apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  labels:
    run: reverseproxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: reverseproxy
